# Generated by Django 3.1.1 on 2020-09-08 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_portal', '0002_userstate'),
    ]

    operations = [
        migrations.AddField(
            model_name='person',
            name='profile_image',
            field=models.ImageField(default='/default.png', upload_to='uploads/'),
        ),
        migrations.AddField(
            model_name='userstate',
            name='profile_image',
            field=models.ImageField(default='/default.png', upload_to='uploads/'),
        ),
    ]
